services:
  app:
    image: premierleagueservice # Nome do container de aplicação
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/premierleague
      SPRING_DATASOURCE_USERNAME: dap
      SPRING_DATASOURCE_PASSWORD: foobar

volumes:
  postgres_data:
