version: '3.8'
services:
  app:
    image: premierleagueservice # Nome do container de aplicação
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/premierleague
      SPRING_DATASOURCE_USERNAME: dap
      SPRING_DATASOURCE_PASSWORD: foobar
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: premierleague
      POSTGRES_USER: dap
      POSTGRES_PASSWORD: foobar
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
